"""add_integration_credentials

Revision ID: d4a41aec02af
Revises: 0001_initial_mvp_tables
Create Date: 2026-06-25 22:11:07.632447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a41aec02af'
down_revision: Union[str, None] = '0001_initial_mvp_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('athlete_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_integration_credentials_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_credentials')),
    sa.UniqueConstraint('user_id', 'provider', name='uq_integration_credentials_user_id_provider')
    )
    op.create_index(op.f('ix_integration_credentials_user_id'), 'integration_credentials', ['user_id'], unique=False)
    op.drop_constraint(op.f('uq_profiles_email'), 'profiles', type_='unique')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_profiles_email'), 'profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_integration_credentials_user_id'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    # ### end Alembic commands ###
