"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

type Lang = "vi" | "en";

interface LanguageContextProps {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    // Nav
    "nav.calendar": "Lịch tập",
    "nav.planBuilder": "Xây dựng kế hoạch",
    "nav.profilesZones": "Chỉ số & Vùng tập",
    "nav.communityFeed": "Bảng tin cộng đồng",
    "nav.profile": "Trang cá nhân",
    "nav.aiCoachSettings": "Cấu hình AI Coach",
    "nav.devicesApps": "Thiết bị & Ứng dụng",
    "nav.billing": "Cửa hàng",
    "nav.help": "Trung tâm trợ giúp",
    "nav.collapse": "Thu gọn",
    "nav.expand": "Mở rộng",
    "nav.training": "Luyện tập",
    "nav.insights": "Phân tích",
    "nav.community": "Cộng đồng",
    "nav.account": "Tài khoản",
    "nav.support": "Hỗ trợ",
    "nav.about": "Về chúng tôi",

    // Calendar
    "calendar.friendSuggestions": "Gợi ý kết bạn",
    "calendar.findFriends": "Tìm bạn bè",
    "calendar.follow": "Theo dõi",
    "calendar.communityActivities": "Hoạt động cộng đồng",
    "calendar.selectDate": "Chọn ngày",
    "calendar.today": "Hôm nay",
    "calendar.rest": "Nghỉ ngơi",
    "calendar.restDay": "Ngày nghỉ",
    "calendar.noWorkouts": "Tháng này chưa có workout",
    "calendar.noWorkoutsDesc": "Generate plan để xem lịch tập demo trong Calendar.",
    "calendar.noResults": "Không có kết quả phù hợp",
    "calendar.noResultsDesc": "Thử xóa tìm kiếm hoặc đổi bộ lọc.",
    "calendar.newRunner": "Runner mới tham gia",
    "calendar.loading": "Đang tải Calendar",
    "calendar.errorTitle": "Không tải được Calendar",
    "calendar.errorDesc": "Dữ liệu mock đang gặp lỗi. Bạn có thể thử tải lại.",
    "calendar.reload": "Tải lại",
    "calendar.minutes": "phút",
    "calendar.noDuration": "Không có thời lượng",
    "calendar.mapTitle": "Bản đồ hoạt động {title}",
    "calendar.planned": "Đã lên kế hoạch",
    "calendar.completed": "Đã hoàn thành",
    "calendar.skipped": "Đã bỏ qua",
    "calendar.prevMonth": "Tháng trước",
    "calendar.nextMonth": "Tháng sau",
    "calendar.monthView": "Lịch tháng",
    "calendar.workout": "Bài tập",
    "calendar.strength": "Luyện sức mạnh",
    "calendar.weekday.mon": "T2",
    "calendar.weekday.tue": "T3",
    "calendar.weekday.wed": "T4",
    "calendar.weekday.thu": "T5",
    "calendar.weekday.fri": "T6",
    "calendar.weekday.sat": "T7",
    "calendar.weekday.sun": "CN",

    // Profile
    "profile.title": "Trang cá nhân",
    "profile.subtitle": "Quản lý thông tin demo và chỉ số thể thao cơ bản.",
    "profile.personalInfo": "Thông tin cá nhân",
    "profile.firstName": "Tên",
    "profile.lastName": "Họ",
    "profile.email": "Email",
    "profile.dob": "Ngày sinh",
    "profile.gender": "Giới tính",
    "profile.primarySport": "Môn thể thao chính",
    "profile.height": "Chiều cao (cm)",
    "profile.weight": "Cân nặng (kg)",
    "profile.save": "Lưu thay đổi",
    "profile.saving": "Đang lưu...",
    "profile.saved": "Đã lưu",
    "profile.saveError": "Lỗi khi lưu",
    "profile.autosave": "Tự động lưu",
    "profile.avatarPlaceholder": "Ảnh đại diện chỉ là placeholder trong frontend phase.",
    "profile.uploadPhoto": "Tải lên/Thay đổi ảnh",
    "profile.gender.none": "Không muốn tiết lộ",
    "profile.gender.female": "Nữ",
    "profile.gender.male": "Nam",
    "profile.gender.other": "Khác",
    "profile.sport.running": "Chạy bộ",
    "profile.sport.cycling": "Đạp xe",
    "profile.sport.swimming": "Bơi lội",

    // Devices
    "devices.title": "Thiết bị & Ứng dụng",
    "devices.subtitle": "Mô phỏng Garmin, Coros và UpRace. Kết nối Strava là thật.",
    "devices.provider": "Nhà cung cấp",
    "devices.status": "Trạng thái",
    "devices.permissions": "Quyền truy cập",
    "devices.action": "Hành động",
    "devices.connected": "Đã kết nối",
    "devices.notConnected": "Chưa kết nối",
    "devices.sync": "Đồng bộ",
    "devices.syncing": "Đang đồng bộ...",
    "devices.disconnect": "Ngắt kết nối",
    "devices.connect": "Kết nối",
    "devices.errorLoading": "Không tải được tích hợp",
    "devices.errorLoadingDesc": "Có lỗi xảy ra khi tải dữ liệu.",
    "devices.disconnectTitle": "Ngắt kết nối tích hợp",
    "devices.disconnectConfirm": "Bạn muốn ngắt kết nối {provider}?",
    "devices.noPermissions": "Chưa có quyền truy cập",
    "devices.syncError": "Lỗi đồng bộ: ",
    "devices.connecting": "Đang kết nối...",
    "devices.error": "Lỗi",
    "auth.loginTitle": "Đăng nhập",
    "auth.loginSubtitle": "Dùng email hoặc Google mock để vào không gian SLABAI.",
    "auth.googleLogin": "Đăng nhập bằng Google",
    "auth.googleRegister": "Đăng ký bằng Google",
    "auth.rememberMe": "Ghi nhớ đăng nhập trên thiết bị này",
    "auth.sendLoginLink": "Gửi link đăng nhập",
    "auth.sendRegisterLink": "Gửi link đăng ký",
    "auth.haveAccount": "Đã có tài khoản?",
    "auth.noAccount": "Chưa có tài khoản?",
    "auth.register": "Đăng ký",
    "auth.login": "Đăng nhập",
    "auth.sendError": "Không thể gửi mã xác thực.",
    "auth.googleError": "Không thể đăng nhập bằng Google.",
    "auth.goBack": "Quay lại",
    "auth.otpSentText": "Chúng tôi đã gửi một liên kết xác thực đến địa chỉ email:",
    "auth.otpCheckEmailPrefix": "Vui lòng kiểm tra hộp thư đến (và cả thư rác) của bạn để bấm vào liên kết và hoàn tất việc ",
    "auth.registerWord": "đăng ký",
    "auth.loginWord": "đăng nhập",
    "auth.registerEmailTitle": "Đăng ký bằng email",
    "auth.registerEmailSubtitle": "Nhận mã xác thực để tạo tài khoản SLABAI demo.",
    "auth.legalCopy": "Không có email thật nào được gửi trong prototype này.",
    "auth.loginVerifyTitle": "Xác thực đăng nhập",
    "auth.loginVerifySubtitle": "Sau khi xác thực, bạn sẽ vào Dashboard placeholder.",
    "auth.registerVerifyTitle": "Xác thực đăng ký",
    "auth.registerVerifySubtitle": "Hoàn tất xác thực để chọn môn thể thao chính.",
    "coach.title": "Cấu hình AI Coach",
    "coach.subtitle": "Điều chỉnh giọng điệu và mức giải thích của coach demo.",
    "coach.vibe": "Giọng điệu Coach",
    "coach.vibe.casual": "Thân thiện",
    "coach.vibe.professional": "Chuyên nghiệp",
    "coach.style": "Kiểu giải thích",
    "coach.style.short": "Ngắn gọn",
    "coach.style.detailed": "Chi tiết",
    "coach.saving": "Đang lưu...",
    "coach.saved": "Đã lưu",
    "billing.title": "Cửa hàng",
    "billing.subtitle": "Cổng thanh toán chỉ được giả lập trong phiên bản demo này.",
    "billing.subscription": "Gói đăng ký",
    "billing.status": "Trạng thái: ",
    "billing.methods": "Phương thức thanh toán",
    "billing.noMethods": "Chưa có phương thức thanh toán",
    "billing.noMethodsDesc": "Thêm phương thức giả lập để kiểm tra giao diện. Không phát sinh giao dịch thực tế.",
    "billing.addMethod": "Thêm thẻ thanh toán",
    "billing.ending": " số cuối ",
    "help.title": "Trung tâm trợ giúp",
    "help.subtitle": "Tìm câu trả lời về account, training plan và integrations mock.",
    "help.searchLabel": "Tìm kiếm chủ đề",
    "help.searchPlaceholder": "Tìm trợ giúp",
    "help.noResults": "Không có kết quả",
    "help.noResultsDesc": "Thử từ khóa khác hoặc xóa tìm kiếm.",
    "help.articlesCount": "{count} bài viết",
    "help.trustTitle": "An toàn & Tin cậy",
    "help.openArticle": "Mở bài viết demo",
    "help.category.gettingStarted": "Bắt đầu với SLABAI",
    "help.trustDesc": "SLABAI cung cấp gợi ý tập luyện mang tính tham khảo, không thay thế tư vấn y tế hoặc huấn luyện chuyên môn trực tiếp.",
    "insights.title": "Chỉ số & Vùng tập",
    "insights.subtitle": "Hiểu pace profile và vùng tập luyện của bạn qua dữ liệu mock.",
    "insights.sport": "Môn thể thao",
    "insights.range": "Khoảng thời gian",
    "insights.running": "Chạy bộ",
    "insights.cycling": "Đạp xe",
    "insights.swimming": "Bơi lội",
    "insights.askCoach": "Hỏi AI Coach",
    "insights.aerobicThreshold": "Ngưỡng hiếu khí",
    "insights.threshold": "Ngưỡng cường độ",
    "insights.vo2max": "VO₂ Max",
    "insights.sprint": "Bứt tốc",
    "insights.paceProfile": "Biểu đồ Pace",
    "insights.profileMeta": "Môn: {sport}. Khoảng thời gian: {range}.",
    "insights.openChart": "Mở biểu đồ",
    "insights.collapse": "Thu gọn",
    "insights.duration": "Thời lượng",
    "insights.pace": "Pace",
    "insights.durationLabel": "Thời lượng {label}",
    "insights.emptyTitle": "Chưa đủ dữ liệu",
    "insights.emptyDesc": "Khi có thêm hoạt động, SLABAI sẽ hiển thị pace profile và zone.",
    "insights.errorTitle": "Không tải được biểu đồ",
    "insights.errorDesc": "Mock chart đang gặp lỗi. Thử tải lại route này.",
    "insights.trust": "SLABAI cung cấp gợi ý tập luyện mang tính tham khảo, không thay thế tư vấn y tế hoặc huấn luyện chuyên môn trực tiếp.",
    // Community
    "community.title": "Cộng đồng",
    "community.subtitle": "Theo dõi hoạt động, thử thách và câu lạc bộ trong cộng đồng SLABAI.",
    "community.filter.following": "Đang theo dõi",
    "community.filter.all": "Tất cả",
    "community.profile.following": "Đang theo dõi",
    "community.profile.followers": "Người theo dõi",
    "community.profile.activities": "Hoạt động",
    "community.profile.streak": "Chuỗi ngày",
    "community.clubs": "Câu lạc bộ",
    "community.challenges": "Thử thách",
    "community.challenges.days": "ngày",
    "community.suggestions": "Gợi ý theo dõi",
    "community.follow": "Theo dõi",
    "community.following": "Đã theo dõi",
    "community.distance": "Quãng đường",
    "community.pace": "Pace",
    "community.time": "Thời gian",
    "community.kudos": "Kudos",
    "community.comment": "Bình luận",
    "community.filterCurrent": "Feed filter hiện tại: {filter}",
    "community.emptyTitle": "Feed đang trống",
    "community.emptyDesc": "Khi bạn theo dõi vận động viên, hoạt động của họ sẽ xuất hiện tại đây.",
    "community.errorTitle": "Không tải được Community",
    "community.errorDesc": "Thử tải lại để xem feed mock.",
    "login": "Đăng nhập",
    "logout": "Đăng xuất",
  },
  en: {
    // Nav
    "nav.calendar": "Calendar",
    "nav.planBuilder": "Plan Builder",
    "nav.profilesZones": "Profiles & Zones",
    "nav.communityFeed": "Community Feed",
    "nav.profile": "Profile",
    "nav.aiCoachSettings": "AI Coach Settings",
    "nav.devicesApps": "Devices & Apps",
    "nav.billing": "Store",
    "nav.help": "Help Center",
    "nav.collapse": "Collapse",
    "nav.expand": "Expand",
    "nav.training": "Training",
    "nav.insights": "Insights",
    "nav.community": "Community",
    "nav.account": "Account",
    "nav.support": "Support",
    "nav.about": "About Us",

    // Calendar
    "calendar.friendSuggestions": "Friend Suggestions",
    "calendar.findFriends": "Find Friends",
    "calendar.follow": "Follow",
    "calendar.communityActivities": "Community Activities",
    "calendar.selectDate": "Select Date",
    "calendar.today": "Today",
    "calendar.rest": "Rest",
    "calendar.restDay": "Rest Day",
    "calendar.noWorkouts": "No workouts this month",
    "calendar.noWorkoutsDesc": "Generate plan to see demo training schedule in Calendar.",
    "calendar.noResults": "No matching results",
    "calendar.noResultsDesc": "Try clearing search or changing filters.",
    "calendar.newRunner": "New runner joined",
    "calendar.loading": "Loading Calendar",
    "calendar.errorTitle": "Failed to load Calendar",
    "calendar.errorDesc": "Mock data is failing. You can try reloading.",
    "calendar.reload": "Reload",
    "calendar.minutes": "minutes",
    "calendar.noDuration": "No duration",
    "calendar.mapTitle": "Activity map {title}",
    "calendar.planned": "Planned",
    "calendar.completed": "Completed",
    "calendar.skipped": "Skipped",
    "calendar.prevMonth": "Previous month",
    "calendar.nextMonth": "Next month",
    "calendar.monthView": "Month view",
    "calendar.workout": "Workout",
    "calendar.strength": "Strength training",
    "calendar.weekday.mon": "Mon",
    "calendar.weekday.tue": "Tue",
    "calendar.weekday.wed": "Wed",
    "calendar.weekday.thu": "Thu",
    "calendar.weekday.fri": "Fri",
    "calendar.weekday.sat": "Sat",
    "calendar.weekday.sun": "Sun",

    // Profile
    "profile.title": "Profile",
    "profile.subtitle": "Manage demo info and basic athletic metrics.",
    "profile.personalInfo": "Personal Information",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.email": "Email",
    "profile.dob": "Date of Birth",
    "profile.gender": "Gender",
    "profile.primarySport": "Primary Sport",
    "profile.height": "Height (cm)",
    "profile.weight": "Weight (kg)",
    "profile.save": "Save changes",
    "profile.saving": "Saving...",
    "profile.saved": "Saved",
    "profile.saveError": "Save Error",
    "profile.autosave": "Autosave",
    "profile.avatarPlaceholder": "Avatar photo is only a placeholder in the frontend phase.",
    "profile.uploadPhoto": "Upload/change photo",
    "profile.gender.none": "Prefer not to say",
    "profile.gender.female": "Female",
    "profile.gender.male": "Male",
    "profile.gender.other": "Other",
    "profile.sport.running": "Running",
    "profile.sport.cycling": "Cycling",
    "profile.sport.swimming": "Swimming",

    // Devices
    "devices.title": "Devices & Apps",
    "devices.subtitle": "Garmin, Coros and UpRace simulated. Strava integration is real.",
    "devices.provider": "Provider",
    "devices.status": "Status",
    "devices.permissions": "Permissions",
    "devices.action": "Action",
    "devices.connected": "Connected",
    "devices.notConnected": "Not connected",
    "devices.sync": "Sync",
    "devices.syncing": "Syncing...",
    "devices.disconnect": "Disconnect",
    "devices.connect": "Connect",
    "devices.errorLoading": "Failed to load integrations",
    "devices.errorLoadingDesc": "An error occurred while loading data.",
    "devices.disconnectTitle": "Disconnect integration",
    "devices.disconnectConfirm": "Are you sure you want to disconnect {provider}?",
    "devices.noPermissions": "No permissions yet",
    "devices.syncError": "Sync error: ",
    "devices.connecting": "Connecting...",
    "devices.error": "Error",
    "auth.loginTitle": "Log In",
    "auth.loginSubtitle": "Use email or Google mock to enter SLABAI space.",
    "auth.googleLogin": "Log in with Google",
    "auth.googleRegister": "Register with Google",
    "auth.rememberMe": "Remember login on this device",
    "auth.sendLoginLink": "Send login link",
    "auth.sendRegisterLink": "Send registration link",
    "auth.haveAccount": "Already have an account?",
    "auth.noAccount": "Don't have an account?",
    "auth.register": "Register",
    "auth.login": "Log In",
    "auth.sendError": "Failed to send verification code.",
    "auth.googleError": "Failed to log in with Google.",
    "auth.goBack": "Go Back",
    "auth.otpSentText": "We have sent a verification link to your email address:",
    "auth.otpCheckEmailPrefix": "Please check your inbox (and spam folder) and click the link to complete your ",
    "auth.registerWord": "registration",
    "auth.loginWord": "login",
    "auth.registerEmailTitle": "Register with email",
    "auth.registerEmailSubtitle": "Receive verification code to create SLABAI demo account.",
    "auth.legalCopy": "No real emails are sent in this prototype.",
    "auth.loginVerifyTitle": "Login verification",
    "auth.loginVerifySubtitle": "After verification, you will enter the Dashboard placeholder.",
    "auth.registerVerifyTitle": "Registration verification",
    "auth.registerVerifySubtitle": "Complete verification to select your primary sport.",
    "coach.title": "AI Coach Settings",
    "coach.subtitle": "Adjust tone and explanation levels of the demo coach.",
    "coach.vibe": "Coach vibe",
    "coach.vibe.casual": "Casual",
    "coach.vibe.professional": "Professional",
    "coach.style": "Explanation style",
    "coach.style.short": "Short",
    "coach.style.detailed": "Detailed",
    "coach.saving": "Saving...",
    "coach.saved": "Saved",
    "billing.title": "Store",
    "billing.subtitle": "Payment gateway is simulated in this frontend demo phase only.",
    "billing.subscription": "Subscription",
    "billing.status": "Status: ",
    "billing.methods": "Payment methods",
    "billing.noMethods": "No payment methods yet",
    "billing.noMethodsDesc": "Add a mock payment method to inspect UI state changes. No actual transactions occur.",
    "billing.addMethod": "Add payment method",
    "billing.ending": " ending ",
    "help.title": "Help Center",
    "help.subtitle": "Find answers regarding account, training plan, and simulated integrations.",
    "help.searchLabel": "Search topics",
    "help.searchPlaceholder": "Search help...",
    "help.noResults": "No results found",
    "help.noResultsDesc": "Try a different keyword or clear search.",
    "help.articlesCount": "{count} articles",
    "help.trustTitle": "Trust & safety",
    "help.openArticle": "Open demo article",
    "help.category.gettingStarted": "Getting Started",
    "help.trustDesc": "SLABAI provides training recommendations for reference only, not replacing medical advice or direct professional coaching.",
    "insights.title": "Profiles & Zones",
    "insights.subtitle": "Understand your pace profile and training zones with mock data.",
    "insights.sport": "Sport",
    "insights.range": "Time range",
    "insights.running": "Running",
    "insights.cycling": "Cycling",
    "insights.swimming": "Swimming",
    "insights.askCoach": "Ask AI Coach",
    "insights.aerobicThreshold": "Aerobic threshold",
    "insights.threshold": "Threshold",
    "insights.vo2max": "VO₂ Max",
    "insights.sprint": "Sprint",
    "insights.paceProfile": "Pace profile",
    "insights.profileMeta": "Sport: {sport}. Range: {range}.",
    "insights.openChart": "Open chart",
    "insights.collapse": "Collapse",
    "insights.duration": "Duration",
    "insights.pace": "Pace",
    "insights.durationLabel": "Duration {label}",
    "insights.emptyTitle": "Not enough data",
    "insights.emptyDesc": "When there are more activities, SLABAI will display pace profile and zones.",
    "insights.errorTitle": "Failed to load chart",
    "insights.errorDesc": "Mock chart is encountering errors. Try reloading this route.",
    "insights.trust": "SLABAI provides training recommendations for reference only, not replacing medical advice or direct professional coaching.",
    // Community
    "community.title": "Community",
    "community.subtitle": "Follow activities, challenges and clubs in the SLABAI community.",
    "community.filter.following": "Following",
    "community.filter.all": "All",
    "community.profile.following": "Following",
    "community.profile.followers": "Followers",
    "community.profile.activities": "Activities",
    "community.profile.streak": "Streak",
    "community.clubs": "Clubs",
    "community.challenges": "Challenges",
    "community.challenges.days": "days",
    "community.suggestions": "Suggestions to follow",
    "community.follow": "Follow",
    "community.following": "Following",
    "community.distance": "Distance",
    "community.pace": "Pace",
    "community.time": "Time",
    "community.kudos": "Kudos",
    "community.comment": "Comment",
    "community.filterCurrent": "Current feed filter: {filter}",
    "community.emptyTitle": "Feed is empty",
    "community.emptyDesc": "When you follow athletes, their activities will appear here.",
    "community.errorTitle": "Failed to load Community",
    "community.errorDesc": "Try reloading to see the mock feed.",
    "login": "Log In",
    "logout": "Log Out",
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("vi");

  useEffect(() => {
    const saved = localStorage.getItem("slabai-lang") as Lang;
    if (saved === "vi" || saved === "en") {
      setLangState(saved);
    }
  }, []);

  const setLang = (nextLang: Lang) => {
    setLangState(nextLang);
    localStorage.setItem("slabai-lang", nextLang);
  };

  const t = (key: string): string => {
    return translations[lang][key as keyof typeof translations["vi"]] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
